name: Lottery
main: net.rymate.lottery.Lottery
version: 1
website: http://
author: rymate


description: >
             A lottery plugin that uses item in the inventory instead of iConomy
commands:
  /lottery:
    description: The actual lottery command
    aliases: []
    usage: |
           /<command> <lotteryname>
  /reloadlottery:
    description: Reloads the config
    aliases: []
    usage: |
           /<command> 

